In [1]:
import numpy as np

In [2]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Crea matriz de ceros, se utiliza para visualizar la estructura

In [15]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Crea matriz de uno, se utiliza para visualizar la estructura

In [14]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### genera datos del 1 al 10 y la cantidad es lo que se realiza en este ejercicio

In [18]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### genera una matriz

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Genera numeros al azar

In [23]:
np.random.rand(4, 4)

array([[0.79424471, 0.26955894, 0.60111393, 0.26566763],
       [0.87865863, 0.73989207, 0.32828404, 0.57924773],
       [0.79060459, 0.92784894, 0.31555103, 0.55803149],
       [0.64858829, 0.96159418, 0.73296299, 0.90947216]])

### genera un numero al azar entero

In [40]:
np.random.randint(1, 43, 5)


array([25, 39, 21, 11, 20])

In [44]:
np.random.randint(1, 100,(10, 10))

array([[92, 99, 12, 35, 51, 31, 85, 98, 28,  5],
       [ 3,  9,  9, 43,  9, 24, 27, 59, 24, 62],
       [87, 43, 82, 76, 19, 21, 41, 68, 44, 61],
       [45, 87, 17, 65, 89, 64, 87, 94, 24, 57],
       [ 3, 24, 55, 43, 18, 78, 60, 35, 12, 62],
       [19, 97, 22, 80, 12, 49, 65, 90, 25, 29],
       [61, 93,  6,  7, 46, 99, 57, 89, 25, 35],
       [61, 47, 16, 56, 63, 42, 38,  6, 22, 56],
       [51, 95, 84, 19, 37, 57, 95, 22, 63, 49],
       [48,  1, 21, 85, 23, 28, 95, 87, 14, 28]])

In [60]:
np.random.randint([1, 3, 5, 7, 5], [[45], [16]], dtype=np.uint8)

array([[44, 39, 12, 21, 11],
       [ 4,  8, 13,  7, 10]], dtype=uint8)