In [1]:
import numpy as np

In [2]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

### nombre.ndim se usa para ver las dimencion del array

In [4]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

In [11]:
matriz = np.array([[1,2,3],[4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [12]:
matriz1 = np.array([[1,2,3],[4, 5, 6],[7, 8, 9],[0, 2, 45]])
print(matriz1)
matriz1.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0  2 45]]


2

In [15]:
tensor = np.array([[[1,2,3],[4, 5, 6],[7, 8, 9],[0, 2, 45]],[[1,2,3],[4, 5, 6],[7, 8, 9],[0, 2, 45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

## Agregar o eliminar dimensiones

In [16]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [17]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim

[[1 2 3]]


2

### Reducir el vector

In [19]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [20]:
tensor = np.array([[[1,2,3],[4, 5, 6],[7, 8, 9],[0, 2, 45]],[[1,2,3],[4, 5, 6],[7, 8, 9],[0, 2, 45]]], ndmin = 12)
print(tensor)
tensor.ndim

[[[[[[[[[[[[ 1  2  3]
           [ 4  5  6]
           [ 7  8  9]
           [ 0  2 45]]

          [[ 1  2  3]
           [ 4  5  6]
           [ 7  8  9]
           [ 0  2 45]]]]]]]]]]]]


12

In [21]:
print(tensor, tensor.ndim)
tensor_2 = np.squeeze(tensor)
print(tensor_2, tensor_2.ndim)

[[[[[[[[[[[[ 1  2  3]
           [ 4  5  6]
           [ 7  8  9]
           [ 0  2 45]]

          [[ 1  2  3]
           [ 4  5  6]
           [ 7  8  9]
           [ 0  2 45]]]]]]]]]]]] 12
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]] 3
