In [1]:
import numpy as np


In [3]:
arr = np.random.randint(1, 20, 10)

In [4]:
matriz = arr.reshape(2, 5)
matriz


array([[ 9, 13, 14, 17, 19],
       [ 3,  3, 12, 19, 12]])

In [6]:
arr

array([ 9, 13, 14, 17, 19,  3,  3, 12, 19, 12])

### Trael el numero mayor

In [5]:
arr.max()

19

In [9]:
matriz

array([[ 9, 13, 14, 17, 19],
       [ 3,  3, 12, 19, 12]])

In [10]:
matriz.max(0)

array([ 9, 13, 14, 19, 19])

### coloca la posicion del numero mayor

In [11]:
arr.argmax()

4

In [12]:
matriz.argmax(0)

array([0, 0, 0, 1, 0], dtype=int64)

arr.min()

In [14]:
matriz.min(0)

array([ 3,  3, 12, 17, 12])

In [15]:
arr.argmin(0)

5

In [16]:
matriz.argmin(1)

array([0, 0], dtype=int64)

In [17]:
arr

array([ 9, 13, 14, 17, 19,  3,  3, 12, 19, 12])

### cual es la diferencia entre el numero menor al mayor

In [23]:
arr.ptp()

16

In [22]:
matriz

array([[ 9, 13, 14, 17, 19],
       [ 3,  3, 12, 19, 12]])

In [21]:
matriz.ptp(0)

array([ 6, 10,  2,  2,  7])

### me da el porcentaje que se desee

In [26]:
arr

array([ 9, 13, 14, 17, 19,  3,  3, 12, 19, 12])

In [30]:
np.percentile(arr, 0)

3.0

### me organiza los datos de mayor a menor

In [31]:
arr.sort()
arr

array([ 3,  3,  9, 12, 12, 13, 14, 17, 19, 19])

## entrega la mitad de los datoseje 1, 2, 3 el entrega 2

In [32]:
np.median(arr)

12.5

In [35]:
matriz

array([[ 3,  3,  9, 12, 12],
       [13, 14, 17, 19, 19]])

In [36]:
np.median(matriz,1)

array([ 9., 17.])

### Desviación estándar

In [37]:
np.std(arr)

5.467174773134658

### varianza

In [38]:
np.var(arr)

29.889999999999997

### Contatenar

In [40]:
# entrega la mediana de los datos
np.mean(arr)

12.1

In [43]:
a = np.array([[1, 2], [3, 4]])
b = np.array([4, 6])
a
b

array([4, 6])

In [46]:
a.ndim
b.ndim

1

In [47]:
b = np.expand_dims(b, axis = 0)

In [48]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [4, 6]])

In [50]:
np.concatenate((a, b.T), axis = 1)

array([[1, 2, 4],
       [3, 4, 6]])

In [53]:
# trampuestas
b.T

array([[4],
       [6]])

In [58]:
np.nanpercentile(a,b)

array([[1.12, 1.18]])