# Ejercicio

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)

In [6]:
type (arr)

numpy.ndarray

In [7]:
matriz=[[1,2,3],[4, 5, 6],[7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr 


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[0]

1

In [12]:
arr[0]+arr[5]

7

In [13]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
matriz[0]

array([1, 2, 3])

In [15]:
matriz[0]

array([1, 2, 3])

In [16]:
matriz[0,2]

3

In [17]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[2:5]

array([3, 4, 5])

In [28]:
arr[::2]

array([1, 3, 5, 7, 9])

In [30]:
arr[-3:]

array([7, 8, 9])

In [31]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [34]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])