In [7]:
import numpy as np

In [8]:
arr = np.random.randint(1, 10, (3, 2))

In [9]:
arr.shape

(3, 2)

In [10]:
arr

array([[4, 5],
       [3, 8],
       [7, 9]])

In [11]:
arr.reshape(1, 6)

array([[4, 5, 3, 8, 7, 9]])

In [12]:
arr.reshape(2, 3)

array([[4, 5, 3],
       [8, 7, 9]])

In [13]:
np.reshape(arr,(2, 3))

array([[4, 5, 3],
       [8, 7, 9]])

In [14]:
arr

array([[4, 5],
       [3, 8],
       [7, 9]])

In [15]:
np.reshape(arr,(2, 3), 'C')

array([[4, 5, 3],
       [8, 7, 9]])

In [16]:
np.reshape(arr,(2, 3), 'F')

array([[4, 7, 8],
       [3, 5, 9]])

In [17]:
np.reshape(arr,(2, 3), 'A')

array([[4, 5, 3],
       [8, 7, 9]])

In [55]:
tensor = np.random.randint(1, 100, (5, 6, 3))
print(tensor)
tensor.ndim


[[[10 25 78]
  [36 81 65]
  [47 58 62]
  [25 56  5]
  [21 14 76]
  [19 89 26]]

 [[51 63 44]
  [68 37 98]
  [68 68 15]
  [76 31  8]
  [16 24 57]
  [86 79 72]]

 [[72 52 25]
  [89 25 20]
  [97 64 29]
  [52  5 55]
  [89 29 42]
  [71 51 38]]

 [[93 56 12]
  [59 48 81]
  [11 20 19]
  [46 53  3]
  [47 52 26]
  [10 38 29]]

 [[24 70 33]
  [40 83 52]
  [80 93 71]
  [14 77  9]
  [11 64 42]
  [51 58 95]]]


3

In [56]:
tensor.shape

(5, 6, 3)