In [16]:
import numpy as np

### Se ulitiza para consultar tipo de dato del array 

In [9]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int32')

### Para canviar le tipo de dato que se desea usar

In [7]:
arr = np.array([1, 2, 3, 4], dtype = 'float64')
arr.dtype

dtype('float64')

In [10]:
arr

array([1, 2, 3, 4])

### Para usar los decimales del dato

In [19]:
arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

### Para convertir datos a Boolean

In [12]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr


array([False,  True,  True,  True,  True])

### se convierte en string

In [14]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [15]:
arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)